In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import statistics
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_auc_score
from sklearn.utils import shuffle
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [2]:
train = pd.read_csv("train.csv")
train.head()

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,train_0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,train_1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,train_2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,train_3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,train_4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104

In [3]:
np.array(train.corr)

array(<bound method DataFrame.corr of              ID_code  target    var_0   var_1    var_2   var_3    var_4  \
0            train_0       0   8.9255 -6.7863  11.9081  5.0930  11.4607
1            train_1       0  11.5006 -4.1473  13.8588  5.3890  12.3622
2            train_2       0   8.6093 -2.7457  12.0805  7.8928  10.5825
3            train_3       0  11.0604 -2.1518   8.9522  7.1957  12.5846
4            train_4       0   9.8369 -1.4834  12.8746  6.6375  12.2772
...              ...     ...      ...     ...      ...     ...      ...
199995  train_199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404
199996  train_199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096
199997  train_199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410
199998  train_199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173
199999  train_199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577

          var_5   var_6    var_7  ...  var_190  var_191  var_192  var_193  \
0       -9.2834  5.1187  18.6266  ...   4.4354   3.9642   3.1364   1.6910
1        7.0433  5.6208  16.5338  ...   7.6421   7.7214   2.5837  10.9516
2       -9.0837  6.9427  14.6155  ...   2.9057   9.7905   1.6704   1.6858
3       -1.8361  5.8428  14.9250  ...   4.4666   4.7433   0.7178   1.4214
4        2.4486  5.9405  19.2514  ...  -1.4905   9.5214  -0.1508   9.1942
...         ...     ...      ...  ...      ...      ...      ...      ...
199995  11.6081  5.6709  15.1516  ...   6.1415  13.2305   3.9901   0.9388
199996 -10.5628  5.8802  21.5940  ...   4.9611   4.6549   0.6998   1.8341
199997  -5.4086  4.5555  21.5571  ...   4.0651   5.4414   3.1032   4.8793
199998   0.5339  6.0479  17.0152  ...   2.6840   8.6587   2.7337  11.1178
199999   0.3488  5.2839  15.2058  ...   8.9842   1.6893   0.1276   0.3766

        var_194  var_195  var_196  var_197  var_198  var_199
0       18.5227  -2.3978   7.8784   8.5635  12.7803  -1.0914
1       15.4305   2.0339   8.1267   8.7889  18.3560   1.9518
2       21.6042   3.1417  -6.5213   8.2675  14.7222   0.3965
3       23.0347  -1.2706  -2.9275  10.2922  17.9697  -8.9996
4       13.2876  -1.5121   3.9267   9.5031  17.9974  -8.8104
...         ...      ...      ...      ...      ...      ...
199995  18.0249  -1.7939   2.1661   8.5326  16.6660 -17.8661
199996  22.2717   1.7337  -2.1651   6.7419  15.9054   0.3388
199997  23.5311  -1.5736   1.2832   8.7155  13.8329   4.1995
199998  20.4158  -0.0786   6.7980  10.0342  15.5289 -13.9001
199999  15.2101  -2.4907  -2.2342   8.1857  12.1284   0.1385

[200000 rows x 202 columns]>, dtype=object)

In [4]:
correlation_matrix = train.loc[:, ~train.columns.isin(['ID_code'])].corr()
correlation_matrix

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
target,1.000000,0.052390,0.050343,0.055870,0.011055,0.010915,0.030979,0.066731,-0.003025,0.019584,...,0.055973,0.047114,-0.042858,-0.017709,-0.022838,0.028285,0.023608,-0.035303,-0.053000,0.025434
var_0,0.052390,1.000000,-0.000544,0.006573,0.003801,0.001326,0.003046,0.006983,0.002429,0.004962,...,0.002752,0.000206,-0.005373,0.001616,-0.001514,0.002073,0.004386,-0.000753,-0.005776,0.003850
var_1,0.050343,-0.000544,1.000000,0.003980,0.000010,0.000303,-0.000902,0.003258,0.001511,0.004098,...,0.006627,0.003621,-0.002604,0.001153,-0.002557,-0.000785,-0.000377,-0.004157,-0.004861,0.002287
var_2,0.055870,0.006573,0.003980,1.000000,0.001001,0.000723,0.001569,0.000883,-0.000991,0.002648,...,0.000197,0.001285,-0.003400,0.000549,0.002104,-0.001070,0.003952,0.001078,-0.000877,0.003855
var_3,0.011055,0.003801,0.000010,0.001001,1.000000,-0.000322,0.003253,-0.000774,0.002500,0.003553,...,0.000151,0.002445,-0.001530,-0.001699,-0.001054,0.001206,-0.002800,0.001164,-0.001651,0.000506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
var_195,0.028285,0.002073,-0.000785,-0.001070,0.001206,0.003706,-0.001274,0.001244,0.001854,0.001396,...,0.004571,0.000870,-0.004745,-0.003143,-0.001201,1.000000,0.002517,-0.004170,-0.000536,0.002042
var_196,0.023608,0.004386,-0.000377,0.003952,-0.002800,0.000513,0.002880,0.005378,0.001045,-0.003242,...,-0.000847,0.002466,-0.001386,-0.005308,-0.005040,0.002517,1.000000,-0.000454,0.000253,0.000607
var_197,-0.035303,-0.000753,-0.004157,0.001078,0.001164,-0.000046,-0.000535,-0.003565,0.003466,-0.004583,...,-0.004974,0.000906,-0.000527,0.005068,0.000884,-0.004170,-0.000454,1.000000,0.001183,0.004991
var_198,-0.053000,-0.005776,-0.004861,-0.000877,-0.001651,-0.001821,-0.000953,-0.003025,0.000650,0.002950,...,-0.000153,-0.000067,0.003451,0.001646,0.003194,-0.000536,0.000253,0.001183,1.000000,-0.004731
var_199,0.025434,0.003850,0.002287,0.003855,0.000506,-0.000786,0.002767,0.006096,-0.001457,0.000854,...,-0.000404,0.003595,-0.001239,-0.000552,-0.005615,0.002042,0.000607,0.004991,-0.004731,1.000000

In [5]:
np.array(correlation_matrix).shape

(201, 201)

In [6]:
# Define the threshold
threshold = 0.3

# Iterate over the correlation matrix and print correlations exceeding the threshold
for i in range(correlation_matrix.shape[0]):
    for j in range(correlation_matrix.shape[1]):
        if i != j and correlation_matrix.iloc[i, j] > threshold:  # Avoid self-correlations
            print(f'Correlation between {correlation_matrix.columns[i]} and {correlation_matrix.columns[j]}: {correlation_matrix.iloc[i, j]}')

In [7]:
# Define the threshold
threshold = 0.3

# Iterate over the correlation matrix and print correlations exceeding the threshold
for i in range(correlation_matrix.shape[0]):
    for j in range(correlation_matrix.shape[1]):
        if correlation_matrix.iloc[i, j] > threshold and i != j:  # Avoid self-correlations
            print(f'Correlation between {correlation_matrix.columns[i]} and {correlation_matrix.columns[j]}: {correlation_matrix.iloc[i, j]}')

In [8]:
y = train.loc[:, 'target']
x = train.loc[:, ~train.columns.isin(['ID_code', 'target'])]
x.head()

,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,-4.9200,5.7470,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,3.1468,8.0851,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,-4.9193,5.9525,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,-5.8609,8.2450,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,6.2654,7.6784,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104

In [9]:
scaler = StandardScaler()

x_scaled = scaler.fit_transform(x)

x = pd.DataFrame(x_scaled, columns = x.columns)
x.head()

,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,-0.577102,-1.273737,0.451707,-0.833709,0.235571,-0.536430,-0.334926,0.608751,-1.561580,-1.473796,...,0.263374,-1.149158,0.817469,-0.411013,0.168705,-1.578117,1.022131,-0.373968,-1.026398,0.214135
1,0.269959,-0.622138,1.190360,-0.688846,0.790975,1.539900,0.244461,-0.003525,0.858974,0.419300,...,0.966611,0.093605,0.443623,1.908764,-0.817594,1.522342,1.067654,-0.129400,0.825417,0.505685
2,-0.681113,-0.276066,0.516988,0.536516,-0.305477,-0.511033,1.769839,-0.564749,-1.561370,-1.307408,...,-0.072093,0.777997,-0.174131,-0.412316,1.151591,2.297370,-1.617906,-0.695141,-0.381449,0.356681
3,0.125158,-0.129426,-0.667575,0.195355,0.927992,0.410672,0.500633,-0.474201,-1.843910,0.548767,...,0.270216,-0.891456,-0.818468,-0.478548,1.607869,-0.789517,-0.959020,1.501744,0.697118,-0.543502
4,-0.277303,0.035610,0.817683,-0.077829,0.738607,0.955574,0.613372,0.791544,1.794753,0.090006,...,-1.036191,0.688988,-1.405987,1.468536,-1.501101,-0.958473,0.297627,0.645537,0.706318,-0.525375

In [10]:
x_scaled

array([[-0.57710174, -1.27373702,  0.45170728, ..., -0.37396811,
        -1.02639785,  0.21413482],
       [ 0.26995857, -0.62213756,  1.19036045, ..., -0.12939961,
         0.82541712,  0.50568523],
       [-0.68111341, -0.2760664 ,  0.51698836, ..., -0.69514059,
        -0.38144932,  0.35668144],
       ...,
       [ 0.17870987, -0.84546901, -0.07667568, ..., -0.20904171,
        -0.67680579,  0.72102365],
       [-0.31746727, -1.72398014,  1.09630117, ...,  1.22180338,
        -0.11352617, -1.01298853],
       [ 0.06456676, -1.00810962,  0.53130173, ..., -0.78389704,
        -1.24290845,  0.33196403]])

In [11]:
from sklearn.decomposition import PCA



n_components = 2  # You can adjust this based on your needs
pca = PCA(n_components=n_components)

# Fit PCA on the training data and transform both training and testing data
x_PCA = pca.fit_transform(x)

x_PCA

array([[ 0.41962809, -0.94324347],
       [ 1.13537291, -0.5077959 ],
       [-0.30912218,  0.21001477],
       ...,
       [ 0.24638529,  0.05313503],
       [-1.9030497 , -0.88385371],
       [-1.35653461,  0.55772299]])

In [12]:
type(x_PCA), x_PCA.shape

(numpy.ndarray, (200000, 2))

In [13]:
X_train, X_test, y_train, y_test = train_test_split(x_PCA, y, train_size = 0.8)

In [ ]:
%%time

# Criando o modelo classificador com o otimizador ADAM : 

mlp_with_adam = MLPClassifier(solver = 'adam', max_iter = 350)


n_neurons = [
    (i, j) for i in range(1, 10) for j in range(1, 5)
] + [
    (i, j, k) for i in range(1, 10) for j in range(1, 10) for k in range(1, 5)
]

actv = ['logistic', 'tanh']

parameters = {'hidden_layer_sizes': n_neurons,
             'activation' : actv}

# O GridSearch serÃ¡ com os dados de treinamento : 

mlp_adam_clf = GridSearchCV(estimator = mlp_with_adam, param_grid = parameters, cv = 10, scoring='accuracy').fit(X_train, y_train)

bparam_adam_hidd = mlp_adam_clf.best_params_['hidden_layer_sizes']
bparam_adam_actv = mlp_adam_clf.best_params_['activation']

print(f"The best param is with layers : {bparam_adam_hidd}, activation : {bparam_adam_actv} and the accuracy is : {mlp_adam_clf.best_score_}")

In [ ]:
%%time


# Fazendo um loop para pegar a acurÃ¡cia mÃ©dia do classificador nos dados de treino: 

result_ml_adam = list()

mlp_adam = MLPClassifier(hidden_layer_sizes = bparam_adam_hidd, activation = bparam_adam_actv, 
                         solver = 'adam', max_iter = 350)


for i in range(10):
    x, y = shuffle(X_train, y_train, random_state = 42)
    result_ml_adam.append(np.mean(cross_val_score(mlp_adam, x, y, cv = 10)))

result_ml_adam = np.array(result_ml_adam)
print(f"The accuracy for mlp is {np.mean(result_ml_adam)} +- {statistics.stdev(result_ml_adam)}")

In [ ]:
# Pegando os dados para a curva AUC gerada pela rede MLP com o ADAM : 

y_pred_proba_adam = mlp_adam.fit(X_train, y_train).predict_proba(X_test)[:, 1]

fpr_adam, tpr_adam, thresholds_adam = metrics.roc_curve(y_test,  y_pred_proba_adam)
auc_adam = metrics.roc_auc_score(y_test, y_pred_proba_adam)

print(f"The AUC value for the mlp using adam is : {auc_adam}")

In [ ]:
plt.plot(fpr_adam, tpr_adam, label="data 1, auc adam = "+str(auc_adam), linestyle = '-', color = 'black')
plt.legend(loc=4)